.build:
  image: node:20.9.0
  script:
    - npm ci
    - ./clone_projects.sh
    - ./build.sh

build:
  extends:
    - .build
  stage: build
  variables:
    C0_GLOBAL_BASE: https://code0-tech.gitlab.io/-/telescopium/-/jobs/$CI_JOB_ID/artifacts/dist
  after_script:
    - node scripts/local_link_suffixer.js
    - |
      echo -e "\e[0Ksection_start:`date +%s`:glpa_summary\r\e[0KHeader of the summary"
      echo "Documentation preview available at ${C0_GLOBAL_BASE}/index.html"
      echo -e "\e[0Ksection_end:`date +%s`:glpa_summary\r\e[0K"
  artifacts:
    paths:
      - dist
    expire_in: 7 days
  rules:
    - if: ($CI_COMMIT_BRANCH != "build-branch" || $C0_TRIGGER_REF != "refs/heads/main") && $CI_COMMIT_BRANCH != "glpa/main"

pages:
  extends:
    - .build
  stage: deploy
  after_script:
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
  rules:
    - if: ($CI_COMMIT_BRANCH == "build-branch" && $C0_TRIGGER_REF == "refs/heads/main") || $CI_COMMIT_BRANCH == "glpa/main"
